### PR TITLE
Include delayed jobs plugin

### LINKED ISSUE #63: DelayedJob middleware
Allow tracking exceptions from DelayedJob

### PR DESCRIPTION
**Pull request by t-romani**
Closes #63 
Now one can catch exceptions while using Delayed Job.
The plugin hooks to jobs lifecycle.

Included it amongst middlewares just to keep consistency.

### CODE REVIEW

File: bin/delayed_job [hunk 1]
```diff
@@ -0,0 +1,5 @@
+#!/usr/bin/env ruby
```
Comment (brunvez) [inline bin/delayed_job:1]: Shouldn't this be inside the `dummy` app?

File: db/migrate/20200616151049_create_delayed_jobs.rb [hunk 2]
```diff
@@ -0,0 +1,22 @@
+class CreateDelayedJobs < ActiveRecord::Migration[6.0]
```
Comment (brunvez) [inline db/migrate/20200616151049_create_delayed_jobs.rb:1]: Same, dummy app

File: lib/exception_hunter/middleware/delayed_job_hunter.rb [hunk 3]
```diff
@@ -0,0 +1,58 @@
+require 'delayed_job'
+
+module ExceptionHunter
+  module Middleware
+    class DelayedJobHunter < ::Delayed::Plugin
+      TRACK_AT_RETRY = [0, 3, 6, 10].freeze
```
Comment (brunvez) [inline lib/exception_hunter/middleware/delayed_job_hunter.rb:6]: Rule of three, we might need to extract this in the future. Not needed for now

**Comment by brunvez** [comment]
Tests?
